-- Eshik liniyasi (line_id=11)
-- Apply:
--   psql "host=localhost dbname=ac2 user=postgres password=postgres sslmode=disable" -f migrations/106_eshik_line.sql

BEGIN;

INSERT INTO lines.lines_list (id, line_id, name, status, folder_name)
OVERRIDING SYSTEM VALUE
SELECT 11, 11, 'Eshik liniyasi', true, 'eshik'
WHERE NOT EXISTS (
    SELECT 1 FROM lines.lines_list WHERE line_id = 11
);

UPDATE lines.lines_list
SET name = 'Eshik liniyasi',
    folder_name = 'eshik',
    status = true,
    line_id = 11
WHERE id = 11 OR line_id = 11;

SELECT setval(
    pg_get_serial_sequence('lines.lines_list', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM lines.lines_list), 11)
);

CREATE TABLE IF NOT EXISTS production.eshik_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id BIGINT NOT NULL REFERENCES production.components(id),
    index1 TEXT NOT NULL DEFAULT '',
    index2 TEXT NOT NULL DEFAULT '',
    seriya_raqami TEXT NOT NULL DEFAULT '',
    c_user_id INT REFERENCES auth.users(id),
    c_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT eshik_components_component_un UNIQUE (component_id)
);

CREATE INDEX IF NOT EXISTS idx_eshik_components_component_id
    ON production.eshik_components (component_id);

CREATE TABLE IF NOT EXISTS production.eshik_daily_serial (
    eshik_component_id BIGINT NOT NULL REFERENCES production.eshik_components(id) ON DELETE CASCADE,
    print_date DATE NOT NULL DEFAULT CURRENT_DATE,
    counter INT NOT NULL DEFAULT 0,
    PRIMARY KEY (eshik_component_id, print_date)
);

CREATE TABLE IF NOT EXISTS production.eshik_print_sessions (
    id BIGSERIAL PRIMARY KEY,
    eshik_component_id BIGINT REFERENCES production.eshik_components(id) ON DELETE SET NULL,
    serial TEXT NOT NULL,
    counter INT NOT NULL DEFAULT 0,
    user_id INT NOT NULL REFERENCES auth.users(id),
    c_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    factory_code TEXT NOT NULL DEFAULT '',
    full_name_uz TEXT NOT NULL DEFAULT '',
    seriya_raqami TEXT NOT NULL DEFAULT '',
    index1 TEXT NOT NULL DEFAULT '',
    index2 TEXT NOT NULL DEFAULT '',
    auxiliary_product_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_eshik_print_sessions_component_id
    ON production.eshik_print_sessions (eshik_component_id);

CREATE INDEX IF NOT EXISTS idx_eshik_print_sessions_c_time
    ON production.eshik_print_sessions (c_time DESC);

WITH route_comments(route, comment) AS (
    VALUES
        ('/api/production/eshik/all', 'Eshik liniyasi komponentlar ro''yxati'),
        ('/api/production/eshik/add', 'Eshik liniyasiga komponent qo''shish'),
        ('/api/production/eshik/update', 'Eshik liniyasi komponentini yangilash'),
        ('/api/production/eshik/delete', 'Eshik liniyasidan komponentni o''chirish'),
        ('/api/lines/eshik/v2/print', 'Eshik liniyasi: etiketka chop etish'),
        ('/api/lines/eshik/v2/reprint', 'Eshik liniyasi: sessiya bo''yicha qayta chop etish'),
        ('/api/lines/eshik/v2/sessions/last', 'Eshik liniyasi: oxirgi chop etish sessiyalari')
)
UPDATE auth.routes r
SET comment = route_comments.comment
FROM route_comments
WHERE r.route = route_comments.route;

WITH route_comments(route, comment) AS (
    VALUES
        ('/api/production/eshik/all', 'Eshik liniyasi komponentlar ro''yxati'),
        ('/api/production/eshik/add', 'Eshik liniyasiga komponent qo''shish'),
        ('/api/production/eshik/update', 'Eshik liniyasi komponentini yangilash'),
        ('/api/production/eshik/delete', 'Eshik liniyasidan komponentni o''chirish'),
        ('/api/lines/eshik/v2/print', 'Eshik liniyasi: etiketka chop etish'),
        ('/api/lines/eshik/v2/reprint', 'Eshik liniyasi: sessiya bo''yicha qayta chop etish'),
        ('/api/lines/eshik/v2/sessions/last', 'Eshik liniyasi: oxirgi chop etish sessiyalari')
)
INSERT INTO auth.routes (route, comment)
SELECT route_comments.route, route_comments.comment
FROM route_comments
WHERE NOT EXISTS (
    SELECT 1 FROM auth.routes r WHERE r.route = route_comments.route
);

COMMIT;
