-- Qadoqlash liniyasi (line_id=12) + laboratoriya BxData saqlash
-- Apply:
--   psql "host=localhost dbname=ac2 user=postgres password=postgres sslmode=disable" -f migrations/107_qadoqlash_line.sql

BEGIN;

INSERT INTO lines.lines_list (id, line_id, name, status, folder_name)
OVERRIDING SYSTEM VALUE
SELECT 12, 12, 'Qadoqlash Liniyasi', true, 'qadoqlash'
WHERE NOT EXISTS (
    SELECT 1 FROM lines.lines_list WHERE line_id = 12
);

UPDATE lines.lines_list
SET name = 'Qadoqlash Liniyasi',
    folder_name = 'qadoqlash',
    status = true,
    line_id = 12
WHERE id = 12 OR line_id = 12;

SELECT setval(
    pg_get_serial_sequence('lines.lines_list', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM lines.lines_list), 12)
);

CREATE TABLE IF NOT EXISTS lines.lab_bx_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_serial TEXT NOT NULL,
    compressor TEXT NOT NULL DEFAULT '',
    bx_model TEXT NOT NULL DEFAULT '',
    line_num TEXT NOT NULL DEFAULT '',
    point_num TEXT NOT NULL DEFAULT '',
    start_time TEXT NOT NULL DEFAULT '',
    stop_time TEXT NOT NULL DEFAULT '',
    test_time TEXT NOT NULL DEFAULT '',
    bx_result TEXT NOT NULL,
    c_user_id INT REFERENCES auth.users(id),
    c_time TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lab_bx_data_product_serial
    ON lines.lab_bx_data (product_serial);

CREATE INDEX IF NOT EXISTS idx_lab_bx_data_c_time
    ON lines.lab_bx_data (c_time DESC);

COMMIT;
