package api

func (s *ServerModel) Routes() {
	s.Router.POST("/user/login", s.Login)

	api := s.Router.Group("/api")
	api.Use(s.Utils.CheckRole())
	api.POST("/user/create", s.Create)
	api.POST("/user/update", s.UpdateUser)
	api.POST("/user/delete", s.DeleteUser)
	api.POST("/user/getall", s.GetAllUsers)
	api.POST("/user/:id", s.GetUserById)
	api.POST("/user/permission/:id", s.ChangeUserPermission)

	api.POST("/serial/info", s.SerialInfo)
	api.POST("/lab/info", s.LabInfo)

	//TECH
	api.POST("/tech/models/add", s.ModelsAdd)
	api.POST("/tech/models/all", s.ModelsGetAll)
	api.POST("/tech/models/update", s.ModelsUpdate)
	api.POST("/tech/models/status", s.ModelsChangeStatus)
	api.POST("/tech/gscode/upload", s.GsCodeUpload)
	api.POST("/tech/gscode/count", s.GsCodesGetCount)
	api.POST("/tech/gscode/report", s.GsCodesReport)
	api.POST("/tech/lines/add_gp_component", s.LinesAddGpComponent)
	api.POST("/tech/printers/add", s.LinesAddPrinter)
	api.POST("/tech/printers/delete", s.LinesDeletePrinter)
	api.POST("/tech/printers-v2/all", s.PrintersV2GetAll)
	api.POST("/tech/printers-v2/by-line", s.PrintersV2GetByLine)
	api.POST("/tech/printers-v2/get", s.PrinterV2GetByID)
	api.POST("/tech/printers-v2/add", s.PrintersV2Add)
	api.POST("/tech/printers-v2/update-language", s.PrintersV2UpdateLanguage)
	api.POST("/tech/printers-v2/delete", s.PrintersV2Delete)
	api.POST("/tech/printers-v2/local", s.PrintersV2LocalList)
	api.POST("/tech/printers-v2/jobs", s.PrintersV2Jobs)
	api.POST("/tech/printers-v2/detect-language", s.PrintersV2DetectLanguage)
	api.POST("/tech/printers-v2/refresh-gdi", s.PrintersV2RefreshGDI)
	api.POST("/tech/printers-v2/test-print", s.PrintersV2TestPrint)
	api.POST("/tech/printers-v2/metrics", s.PrintersV2Metrics)
	api.POST("/tech/printers-v2/metrics/errors", s.PrintersV2MetricsErrors)
	api.POST("/tech/printers-v2/metrics/reset", s.PrintersV2MetricsReset)
	api.POST("/tech/label-templates/all", s.LabelTemplatesGetAll)
	api.POST("/tech/label-templates/get", s.LabelTemplateGetByID)
	api.POST("/tech/label-templates/create", s.LabelTemplateCreate)
	api.POST("/tech/label-templates/duplicate", s.LabelTemplateDuplicate)
	api.POST("/tech/label-templates/update", s.LabelTemplateUpdate)
	api.POST("/tech/label-templates/delete", s.LabelTemplateDelete)
	api.POST("/tech/label-templates/preview", s.LabelTemplatePreview)
	api.POST("/tech/label-templates/image/upload", s.LabelTemplateImageUpload)
	api.POST("/tech/brands/all", s.BrandsGetAll)
	api.POST("/tech/brand-logos/all", s.BrandLogosGetAll)
	api.POST("/tech/brand-logos/upsert", s.BrandLogoUpsert)
	api.POST("/tech/brand-logos/delete", s.BrandLogoDelete)

	//PRODUCTION
	api.POST("/production/info", s.ProductionInfo)
	api.POST("/production/report/xlsx", s.ProductionReportXlsx)
	api.POST("/production/components/all", s.ProductionComponentsGetAll)
	api.POST("/production/components/add", s.ProductionComponentsAdd)
	api.POST("/production/components/update", s.ProductionComponentsUpdate)
	api.POST("/production/components/delete", s.ProductionComponentsDelete)
	api.POST("/production/components/upload", s.ProductionComponentsUpload)
	api.POST("/production/components/types", s.ProductionComponentTypesGet)
	api.POST("/production/components/units", s.ProductionComponentUnitsGet)
	api.POST("/production/components/template", s.ProductionComponentsTemplate)
	api.POST("/production/components/photo/upload", s.ProductionComponentPhotoUpload)
	api.POST("/production/line_responsibles/all", s.ProductionLineResponsiblesGetAll)
	api.POST("/production/line_responsibles/add", s.ProductionLineResponsiblesAdd)
	api.POST("/production/line_responsibles/delete", s.ProductionLineResponsiblesDelete)
	api.POST("/production/consumption-norm/models", s.ConsumptionNormModels)
	api.POST("/production/consumption-norm/items", s.ConsumptionNormItems)
	api.POST("/production/consumption-norm/lines", s.ConsumptionNormLines)
	api.POST("/production/consumption-norm/update-lines", s.ConsumptionNormUpdateLines)
	api.POST("/production/consumption-norm/add", s.ConsumptionNormAdd)
	api.POST("/production/consumption-norm/delete", s.ConsumptionNormDelete)
	api.POST("/production/consumption-norm/upload", s.ConsumptionNormUpload)
	api.POST("/production/consumption-norm/template", s.ConsumptionNormTemplate)

	api.POST("/production/plan/day", s.ProductionPlanDay)
	api.POST("/production/plan/month", s.ProductionPlanMonth)
	api.POST("/production/plan/save", s.ProductionPlanSave)
	api.POST("/production/plan/report", s.ProductionPlanReport)
	api.POST("/production/plan/dashboard", s.ProductionPlanDashboard)
	api.POST("/production/plan/lock-day", s.ProductionPlanLockDay)
	api.POST("/production/plan/lock-month", s.ProductionPlanLockMonth)
	api.POST("/production/plan/unlock-day", s.ProductionPlanUnlockDay)
	api.POST("/production/plan/unlock-month", s.ProductionPlanUnlockMonth)
	api.POST("/production/plan/allowed-models", s.ProductionPlanAllowedModels)
	api.POST("/production/plan/export", s.ProductionPlanExport)
	api.POST("/production/plan/import", s.ProductionPlanImport)

	api.POST("/production/shifts/get", s.ProductionShiftsGet)
	api.POST("/production/shifts/save", s.ProductionShiftsSave)
	api.POST("/production/eshik/all", s.ProductionEshikGetAll)
	api.POST("/production/eshik/add", s.ProductionEshikAdd)
	api.POST("/production/eshik/update", s.ProductionEshikUpdate)
	api.POST("/production/eshik/delete", s.ProductionEshikDelete)
	api.POST("/production/eshik/export", s.ProductionEshikExport)
	api.POST("/production/eshik/template", s.ProductionEshikTemplate)
	api.POST("/production/eshik/import", s.ProductionEshikImport)

	//LINES
	api.POST("/lines/all", s.LinesGetAll)
	api.POST("/lines/gp_component/all", s.LinesGetGPComponents)
	api.POST("/lines/gp_component/delete", s.LinesGetGPComponentsDelete)
	api.POST("/lines/product/last", s.LinesGetLastComponents)
	api.POST("/lines/product/add", s.LinesAddProduct)
	api.POST("/lines/printers/all", s.LinesGetPrinters)
	api.POST("/lines/product/reprint", s.LinesRePrint)
	api.POST("/lines/balance", s.LinesGetBalance)
	api.POST("/lines/balance/adjust", s.LinesBalanceAdjust)
	api.POST("/lines/balance/transactions", s.LinesBalanceTransactions)
	api.POST("/lines/product/balance", s.LinesProductBalance)
	api.POST("/lines/product/report", s.LinesProductReport)
	api.POST("/lines/last", s.LinesLast)
	api.POST("/lines/report", s.LinesReport)
	api.POST("/lines/auxiliary/report", s.LinesAuxiliaryReport)
	api.POST("/lines/dashboard", s.LinesDashboard)
	api.POST("/lines/reja", s.LinesRejaGet)
	api.POST("/lines/reja/update", s.LinesRejaUpdate)
	api.POST("/lines/brigadir/items", s.LinesBrigadirItems)
	api.POST("/lines/brigadir/confirm", s.LinesBrigadirConfirm)
	api.POST("/lines/brigadir/confirm-all", s.LinesBrigadirConfirmAll)
	api.POST("/lines/yigish/v2/print", s.LinesYigishV2Print)
	api.POST("/lines/yigish/v2/reprint", s.LinesYigishV2RePrint)
	api.POST("/lines/eshik/v2/print", s.LinesEshikV2Print)
	api.POST("/lines/eshik/v2/reprint", s.LinesEshikV2Reprint)
	api.POST("/lines/eshik/v2/sessions/last", s.LinesEshikV2SessionsLast)
	api.POST("/lines/qadoqlash/complete", s.LinesQadoqlashComplete)
	api.POST("/lines/qadoqlash/reprint", s.LinesQadoqlashReprint)
	api.POST("/lines/qadoqlash/sessions/last", s.LinesQadoqlashSessionsLast)

	//WARE
	api.POST("/ware/stock/all", s.WareStockGetAll)
	api.POST("/ware/stock/snapshot", s.WareStockSnapshot)
	api.POST("/ware/gp-products/last", s.WareGPProductBalanceLast)
	api.POST("/ware/gp-products/history", s.WareGPProductBalanceHistory)
	api.POST("/ware/gp-products/report", s.WareGPProductReport)
	api.POST("/ware/income", s.WareIncome)
	api.POST("/ware/income/history", s.WareIncomeHistory)
	api.POST("/ware/upload", s.WareUpload)
	api.POST("/ware/request/build", s.WareRequestBuild)
	api.POST("/ware/request/confirm", s.WareRequestConfirm)
	api.POST("/ware/delivery-notes", s.WareDeliveryNotesList)
	api.POST("/ware/delivery-notes/items", s.WareDeliveryNoteItems)
	api.POST("/ware/delivery-notes/snapshots", s.WareDeliveryNoteSnapshotsList)
	api.POST("/ware/delivery-notes/snapshots/items", s.WareDeliveryNoteSnapshotItems)
	api.POST("/ware/delivery-notes/items/update", s.WareDeliveryNoteItemUpdate)
	api.POST("/ware/delivery-notes/items/confirm", s.WareDeliveryNoteItemConfirm)
	api.POST("/ware/delivery-notes/items/unconfirm", s.WareDeliveryNoteItemUnconfirm)
	api.POST("/ware/delivery-notes/items/confirm-all", s.WareDeliveryNoteItemsConfirmAll)
	api.POST("/ware/delivery-notes/items/unconfirm-all", s.WareDeliveryNoteItemsUnconfirmAll)
	api.POST("/ware/delivery-notes/items/delete", s.WareDeliveryNoteItemDelete)

	//WRITEOFF
	api.POST("/writeoff/responsibles/all", s.WriteoffResponsiblesGetAll)
	api.POST("/writeoff/responsibles/add", s.WriteoffResponsiblesAdd)
	api.POST("/writeoff/responsibles/delete", s.WriteoffResponsiblesDelete)
	api.POST("/writeoff/documents/list", s.WriteoffDocumentsList)
	api.POST("/writeoff/documents/get", s.WriteoffDocumentGet)
	api.POST("/writeoff/documents/create", s.WriteoffDocumentCreate)
	api.POST("/writeoff/documents/delete", s.WriteoffDocumentDelete)
	api.POST("/writeoff/documents/items/save", s.WriteoffDocumentItemsSave)
	api.POST("/writeoff/documents/submit", s.WriteoffDocumentSubmit)
	api.POST("/writeoff/documents/approve", s.WriteoffDocumentApprove)
	api.POST("/writeoff/documents/reject", s.WriteoffDocumentReject)
	api.POST("/writeoff/documents/export", s.WriteoffDocumentExport)
	api.POST("/writeoff/documents/import", s.WriteoffDocumentImport)
	api.POST("/writeoff/documents/template", s.WriteoffDocumentTemplate)
	api.POST("/writeoff/records/list", s.WriteoffRecordsList)
	api.POST("/writeoff/catalog/lines", s.WriteoffCatalogLines)
	api.POST("/writeoff/catalog/items", s.WriteoffCatalogItems)
	api.POST("/writeoff/is-responsible", s.WriteoffIsResponsible)
}
