export const MODEL_FIELD_LABELS: Record<string, string> = {
  id: "ID",
  seriya_raqami: "Seriya raqami",
  acc_serial: "acc_serial",
  modeli: "Modeli",
  sovutgich_turi: "Sovutgich turi",
  qisqa_nomi: "qisqa nomi",
  rangi: "Rangi",
  sotuv_turi: "Sotuv turi",
  gs1_ean13: "GS1 EAN13",
  gost: "GOST",
  taminot_kuchlanishi_v: "Ta'minot kuchlanishi (V)",
  xladagent_miqdori_g: "Xladagent miqdori (g)",
  energiya_samaradorlik_sarfi: "Energiya samaradorlik sarfi (A+)",
  kompressor_nomi: "Kompressor nomi",
  maxalliy_sertifikat: "Maxalliy sertifikat",
  eac_sertifikati: "EAC sertifikati",
  ce_sertifikat: "CE sertifikat",
  ishlab_chiqaruvchi_mamlakat: "Ishlab chiqaruvchi mamlakat",
  korxon_nomi: "Korxona nomi",
  manzil: "Manzil",
  brend: "Brend",
  local_export: "Local/Export",
  netto: "Netto",
  brutto: "Brutto",
  qadoq_hajmi: "Qadoq hajmi",
  mahsulot_hajmi: "Mahsulot hajmi",
  iqlim_sharoitlari: "Iqlim sharoitlari",
  elektr_toki_kuchlanishi_va_turi: "Elektr toki kuchlanishi va turi",
  yoritgich_lampaning_quvvati_vt: "Yoritgich lampaning quvvati (Vt)",
  umumiy_hajmi_l: "Umumiy hajmi (L)",
  sovutgich_kamera_hajmi_l: "Sovutgich kamera hajmi (L)",
  muzlatgich_kamera_hajmi_l: "Muzlatgich kamera hajmi (L)",
  muzlatish_quvvati: "Muzlatish quvvati",
  nominal_tok_quvvati_w: "Nominal tok quvvati (W)",
  freon: "Freon",
  shovqin_darajasi_db: "Shovqin darajasi ichki blok dB",
  odoo_code: "ODOO code",
  door_code: "door_code",
  compressor_serial: "kompressor_serial",
  comment: "comment",
  gs1_data: "GS1 data",
  serial_number: "Serial number",
  status: "Status",
  gscode_count: "GS Code count",
  u_time: "Updated",
}

export function modelFieldLabel(key: string): string {
  return MODEL_FIELD_LABELS[key] ?? key
}
