-- Eshik: model + freeze/ref parts (prefix, indexes, balance components)
-- Apply:
--   psql "host=localhost dbname=ac2 user=postgres password=postgres sslmode=disable" -f migrations/116_eshik_models.sql

BEGIN;

CREATE TABLE IF NOT EXISTS production.eshik_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,
    c_user_id INT REFERENCES auth.users(id),
    c_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT eshik_models_name_un UNIQUE (model_name)
);

CREATE TABLE IF NOT EXISTS production.eshik_model_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eshik_model_id BIGINT NOT NULL REFERENCES production.eshik_models(id) ON DELETE CASCADE,
    door_code TEXT NOT NULL CHECK (door_code IN ('freeze', 'ref')),
    component_id BIGINT NOT NULL REFERENCES production.components(id),
    index1 TEXT NOT NULL DEFAULT '',
    index2 TEXT NOT NULL DEFAULT '',
    seriya_raqami TEXT NOT NULL DEFAULT '',
    CONSTRAINT eshik_model_parts_model_door_un UNIQUE (eshik_model_id, door_code)
);

CREATE INDEX IF NOT EXISTS idx_eshik_model_parts_model_id
    ON production.eshik_model_parts (eshik_model_id);

CREATE INDEX IF NOT EXISTS idx_eshik_model_parts_component_id
    ON production.eshik_model_parts (component_id);

-- Daily counters keyed by part
DROP TABLE IF EXISTS production.eshik_daily_serial;
CREATE TABLE production.eshik_daily_serial (
    eshik_model_part_id BIGINT NOT NULL REFERENCES production.eshik_model_parts(id) ON DELETE CASCADE,
    print_date DATE NOT NULL DEFAULT CURRENT_DATE,
    counter INT NOT NULL DEFAULT 0,
    PRIMARY KEY (eshik_model_part_id, print_date)
);

-- Print sessions: switch to model parts (keep legacy column nullable for old rows)
ALTER TABLE production.eshik_print_sessions
    DROP CONSTRAINT IF EXISTS eshik_print_sessions_eshik_component_id_fkey;

ALTER TABLE production.eshik_print_sessions
    ALTER COLUMN eshik_component_id DROP NOT NULL;

ALTER TABLE production.eshik_print_sessions
    ADD COLUMN IF NOT EXISTS eshik_model_id BIGINT REFERENCES production.eshik_models(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS eshik_model_part_id BIGINT REFERENCES production.eshik_model_parts(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS door_code TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS model_name TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_eshik_print_sessions_model_id
    ON production.eshik_print_sessions (eshik_model_id);

CREATE INDEX IF NOT EXISTS idx_eshik_print_sessions_part_id
    ON production.eshik_print_sessions (eshik_model_part_id);

-- Legacy single-component catalog no longer used
DROP TABLE IF EXISTS production.eshik_components CASCADE;

WITH route_comments(route, comment) AS (
    VALUES
        ('/api/production/eshik/all', 'Eshik liniyasi modellar ro''yxati'),
        ('/api/production/eshik/add', 'Eshik liniyasiga model qo''shish'),
        ('/api/production/eshik/update', 'Eshik liniyasi modelini yangilash'),
        ('/api/production/eshik/delete', 'Eshik liniyasidan modelni o''chirish'),
        ('/api/lines/eshik/v2/print', 'Eshik liniyasi: freeze+ref etiketka chop etish'),
        ('/api/lines/eshik/v2/reprint', 'Eshik liniyasi: sessiya bo''yicha qayta chop etish'),
        ('/api/lines/eshik/v2/sessions/last', 'Eshik liniyasi: oxirgi chop etish sessiyalari')
)
UPDATE auth.routes r
SET comment = route_comments.comment
FROM route_comments
WHERE r.route = route_comments.route;

COMMIT;
